// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_qjSF3BWiQ8hyljsIZjfI7CHK9TzUHhw',
    appId: '1:873867626947:web:67aa17ebc85595ab35d576',
    messagingSenderId: '873867626947',
    projectId: 'againlogin-e858f',
    authDomain: 'againlogin-e858f.firebaseapp.com',
    storageBucket: 'againlogin-e858f.appspot.com',
    measurementId: 'G-51659BW7XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo74Sv4HP8gcE-dhgTqGS7ph33lMUN8Bk',
    appId: '1:873867626947:android:d9e152dfc42ee07d35d576',
    messagingSenderId: '873867626947',
    projectId: 'againlogin-e858f',
    storageBucket: 'againlogin-e858f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2PMFylbIx8jcirzPuV2jvIoFmmxK2DFs',
    appId: '1:873867626947:ios:40729296df6c994c35d576',
    messagingSenderId: '873867626947',
    projectId: 'againlogin-e858f',
    storageBucket: 'againlogin-e858f.appspot.com',
    iosBundleId: 'com.example.loginbalacodenew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2PMFylbIx8jcirzPuV2jvIoFmmxK2DFs',
    appId: '1:873867626947:ios:4dfeedc9d766468d35d576',
    messagingSenderId: '873867626947',
    projectId: 'againlogin-e858f',
    storageBucket: 'againlogin-e858f.appspot.com',
    iosBundleId: 'com.example.loginbalacodenew.RunnerTests',
  );
}
